# -*- coding: utf-8 -*-
"""CustomerServiceAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jln3bwiJnTBNAnC-iTQxkaoXOOpY1vgE
"""

!!pip install litellm

# Important!!!
#
# <---- Set your 'OPENAI_API_KEY' as a secret over there with the "key" icon
#
#
import os
from google.colab import userdata
api_key = userdata.get('Coursera')
os.environ['OPENAI_API_KEY'] = api_key

from litellm import completion
from typing import List, Dict


def generate_response(messages: List[Dict]) -> str:
    """Call LLM to get response"""
    response = completion(
        model="openai/gpt-4o-mini",
        messages=messages,
        max_tokens=1024
    )
    return response.choices[0].message.content


what_function = input("What function do you want to create?")

messages = [
    {"role": "system", "content": "You are a helpful python programmer who always writes a basic Python function based on the user’s description."},
    {"role": "user", "content": what_function}
]

response = generate_response(messages)

messages = [
    {"role": "system", "content": "You are a helpful python programmer who always writes a basic Python function based on the user’s description."},
    {"role": "user", "content": what_function},
    {"role": "assistant", "content": response},
    {"role": "user", "content": "Parse the response to separate the code from the commentary."}
]

response = generate_response(messages)
print(response)

first_prompt_code = input("Share the code that I generated from your first prompt.")

messages = [
    {"role": "system", "content": "You are a helpful python programmer who always adds comprehensive documentation including, Function description, Parameter descriptions, Return value description, Example usage, Edge cases to your code."},
    {"role": "user", "content": first_prompt_code}
]

response = generate_response(messages)
print(response)

